// Generated by CoffeeScript 1.4.0
(function() {

  define(['underscore', 'lib/utils', 'chaplin'], function(_, utils, Chaplin) {
    'use strict';

    var support;
    support = utils.beget(Chaplin.support);
    return support;
  });

}).call(this);
