// Generated by CoffeeScript 1.6.3
define(['underscore', 'lib/utils', 'chaplin'], function(_, utils, Chaplin) {
  'use strict';
  var support;
  support = utils.beget(Chaplin.support);
  return support;
});
