// Generated by CoffeeScript 1.3.3

define(['underscore', 'jquery', 'chaplin'], function(_, jquery, Chaplin) {
  var mediator, utils;
  mediator = Chaplin.mediator;
  utils = Chaplin.utils.beget(Chaplin.utils);
  return utils;
});
