// Generated by CoffeeScript 1.4.0
(function() {

  define(['underscore', 'chaplin'], function(_, Chaplin) {
    'use strict';

    var utils;
    utils = Chaplin.utils.beget(Chaplin.utils);
    return utils;
  });

}).call(this);
